FROM python:3.8 AS test3.8
WORKDIR /diffq-ci
COPY setup.py .
COPY diffq diffq
RUN --mount=type=cache,target=/root/.cache/pip pip install .[test]
COPY test test
COPY .coveragerc .coveragerc
RUN coverage run -m xmlrunner discover test
RUN mkdir -p /coverage && cp -v .coverage.* /coverage && \
    mkdir -p /unittest && cp *.xml /unittest


FROM python:3.9 AS test3.9
WORKDIR /diffq-ci
COPY setup.py .
COPY diffq diffq
RUN --mount=type=cache,target=/root/.cache/pip pip install .[test]
COPY test test
COPY .coveragerc .coveragerc
RUN coverage run -m xmlrunner discover test
RUN mkdir -p /coverage && cp -v .coverage.* /coverage && \
    mkdir -p /unittest && cp *.xml /unittest


FROM python:3.10 AS test3.10
WORKDIR /diffq-ci
COPY setup.py .
COPY diffq diffq
RUN --mount=type=cache,target=/root/.cache/pip pip install .[test]
COPY test test
COPY .coveragerc .coveragerc
RUN coverage run -m xmlrunner discover test
RUN mkdir -p /coverage && cp -v .coverage.* /coverage && \
    mkdir -p /unittest && cp *.xml /unittest


FROM python:3.11 AS test3.11
WORKDIR /diffq-ci
COPY setup.py .
COPY diffq diffq
RUN --mount=type=cache,target=/root/.cache/pip pip install .[test]
COPY test test
COPY .coveragerc .coveragerc
RUN coverage run -m xmlrunner discover test
RUN mkdir -p /coverage && cp -v .coverage.* /coverage && \
    mkdir -p /unittest && cp -v *.xml /unittest


FROM python:latest AS combine
WORKDIR /coverage
RUN --mount=type=cache,target=/root/.cache/pip pip install coverage
COPY diffq diffq
COPY .coveragerc .coveragerc
COPY --from=test3.8 /coverage /coverage
COPY --from=test3.9 /coverage /coverage
COPY --from=test3.10 /coverage /coverage
COPY --from=test3.11 /coverage /coverage
RUN coverage combine && \
    echo "## Test Coverage\n\`\`\`\n" >> summary.md && \
    coverage report | tee -a summary.md && \
    echo "\n\`\`\`" >> summary.md && \
    mkdir -p /coverage/html && coverage html -d /coverage/html


FROM python:3.8 AS build
WORKDIR /build
RUN --mount=type=cache,target=/root/.cache/pip pip install wheel
COPY LICENSE LICENSE
COPY setup.py setup.py
COPY README.md README.md
COPY diffq diffq
RUN pip wheel --no-deps -w /dist .
RUN python setup.py sdist -d /dist


FROM scratch AS results
COPY --from=test3.8 /unittest /unittest/3.8
COPY --from=test3.9 /unittest /unittest/3.9
COPY --from=test3.10 /unittest /unittest/3.10
COPY --from=test3.11 /unittest /unittest/3.11
COPY --from=combine /coverage/html /coverage/html
COPY --from=combine /coverage/summary.md /coverage/summary.md
COPY --from=build /dist /dist
CMD [""]
